site_name: Flutter TeX
theme:
  name: material
  logo: https://raw.githubusercontent.com/Shahxad-Akram/flutter_tex/main/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep navy blue
      accent: navy blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep navy blue
      accent: navy blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.follow
    - navigation.instant
    - content.code.copy
    - content.code.annotate # Allows you to put clickable (1) markers in code
    - search.suggest
    - search.highlight

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

repo_url: https://github.com/Shahxad-Akram/flutter_tex
repo_name: flutter_tex

nav:
  - Home: index.md
  - Installation: Installation.md
  - Math Widgets:
      - Math2SVG: Math2SVG.md
      - TeXWidget: TeXWidget.md
      - TeXView: TeXView.md
  - Configuration:
      - MathJax Configs: MathJax Configs.md
      - Custom Fonts: Custom Fonts.md
  - Examples: Examples.md
