site_name: Flutter TeX
extra:
  flutter_tex_version: "5.2.4"
theme:
  name: material

  logo: https://raw.githubusercontent.com/Shahxad-Akram/flutter_tex/main/logo.png
  favicon: images/favicon.png
  site_url: https://flutter-tex.readthedocs.io

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.follow
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      pygments_style: dracula
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

repo_url: https://github.com/Shahxad-Akram/flutter_tex
repo_name: flutter_tex

plugins:
  - search
  - macros

nav:
  - Home: index.md
  - Installation: installation.md
  - Math Widgets:
      - Math2SVG: math-2-svg.md
      - TeXWidget: tex-widget.md
      - TeXView: tex-view.md
  - Configuration:
      - MathJax Configs: mathjax-configs.md
      - Custom Fonts: custom-fonts.md
  - Examples: examples.md
  - Gallery: gallery.md
